/* Dodge City Urban Infrastructure Monitor – dashboard logic
 * Data comes from window.INFRA_DATA (generated by run_pipeline.py). */
(() => {
  "use strict";
  const D = window.INFRA_DATA;
  if (!D) {
    document.getElementById("loading").textContent = "No data found – run `python run_pipeline.py` first.";
    return;
  }

  // ------------------------------------------------------------------ constants
  const css = (v) => getComputedStyle(document.documentElement).getPropertyValue(v).trim();
  const TYPE = {
    water_pressure:    { label: "Water pressure", color: css("--pressure"), short: "Pressure" },
    streetlight_power: { label: "Streetlight power", color: css("--light"), short: "Lighting" },
    traffic_volume:    { label: "Traffic volume", color: css("--traffic"), short: "Traffic" },
    structural_tilt:   { label: "Structural tilt", color: css("--tilt"), short: "Structural" },
    air_quality:       { label: "Air quality", color: css("--aq"), short: "Air quality" },
  };
  const ACTIONS = {
    main_break_leak: "Dispatch water crew; isolate valves either side of the main and notify affected buildings.",
    pressure_transient: "Review valve/hydrant operations in the window; inspect for surge damage if repeated.",
    pump_station_trip: "Check pump station SCADA and backup power; zone-wide – not a single-asset fault.",
    lamp_outage: "Create relamp work order; verify controller and feed circuit.",
    day_burner: "Replace photocell / check controller schedule – wasting energy in daylight.",
    power_surge: "Inspect ballast/driver and supply voltage; risk of premature lamp failure.",
    road_closure: "Confirm closure with traffic ops; if none scheduled, check detector for obstruction.",
    incident_congestion: "Check for crash / diversion; consider signal timing adjustment.",
    foundation_settlement: "Schedule structural inspection; tilt is accelerating beyond thermal range.",
    local_pollution_event: "Look for nearby emission source (fire, construction dust, idling).",
    regional_aq_event: "Area-wide weather event – issue public advisory if PM2.5 stays elevated.",
  };
  const FAULT_LABEL = {
    main_break_leak: "Main break / leak", pressure_transient: "Pressure transient", pump_station_trip: "Pump station trip",
    lamp_outage: "Lamp outage", day_burner: "Day-burner", power_surge: "Power surge", road_closure: "Road closure",
    incident_congestion: "Incident congestion", foundation_settlement: "Foundation settlement",
    local_pollution_event: "Local pollution", regional_aq_event: "Regional AQ event",
  };
  const times = D.meta.times.map((t) => new Date(t + "Z")); // naive local clock, read via UTC getters
  const N = times.length;
  const center = [D.meta.center[1], D.meta.center[0]];
  const HOME = { center: [center[0] + 0.0015, center[1] - 0.004], zoom: 15.2, pitch: 58, bearing: -22 };

  const byType = (t) => D.assets.features.filter((f) => f.properties.type === t);
  const sensorsById = Object.fromEntries(D.sensors.map((s) => [s.id, s]));
  const assetById = Object.fromEntries(D.assets.features.map((f) => [f.properties.id, f]));

  // active incident lookup per hour
  const activeAt = Array.from({ length: N }, () => []);
  D.incidents.forEach((inc) => { for (let i = inc.start_idx; i <= inc.end_idx; i++) activeAt[i].push(inc); });

  const state = {
    t: 0, playing: false, timer: null, bldgMode: "risk", activeOnly: true,
    types: new Set(Object.keys(TYPE)), selected: null, pitched: true,
  };

  // ------------------------------------------------------------------ helpers
  const fmtDate = (d) => d.toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric", timeZone: "UTC" });
  const fmtHour = (d) => d.toISOString().slice(11, 16) + " CDT";
  const fmtShort = (d) => d.toLocaleDateString("en-US", { month: "short", day: "numeric", timeZone: "UTC" }) + " " + d.toISOString().slice(11, 16);
  const num = (v, d = 1) => (v == null ? "—" : Number(v).toLocaleString("en-US", { maximumFractionDigits: d }));
  const esc = (s) => String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
  const prClass = (p) => (p >= 60 ? "p-hi" : p >= 40 ? "p-md" : "p-lo");

  function squareAround(lon, lat, m) {
    const dx = m / (111320 * Math.cos((lat * Math.PI) / 180)), dy = m / 110540;
    return [[[lon - dx, lat - dy], [lon + dx, lat - dy], [lon + dx, lat + dy], [lon - dx, lat + dy], [lon - dx, lat - dy]]];
  }

  function sensorStatus(s, i) {
    const v = s.values[i];
    if (v == null) return "offline";
    if (activeAt[i].some((inc) => inc.sensor_id === s.id)) return "alarm";
    if (Math.abs(s.z[i] ?? 0) >= 3) return "warning";
    return "normal";
  }

  function sensorGeoJSON(i) {
    return {
      type: "FeatureCollection",
      features: D.sensors.map((s, k) => {
        const status = sensorStatus(s, i);
        const z = Math.abs(s.z[i] ?? 0);
        return {
          type: "Feature", id: k,
          geometry: { type: "Polygon", coordinates: squareAround(s.lon, s.lat, 5) },
          properties: {
            id: s.id, type: s.type, status, value: s.values[i], unit: s.unit, z: s.z[i],
            h: status === "offline" ? 4 : 12 + Math.min(z, 20) * 2.6,
            color: status === "alarm" ? css("--bad") : status === "warning" ? css("--warn") : status === "offline" ? css("--off") : TYPE[s.type].color,
          },
        };
      }),
    };
  }

  function incidentPoints(i) {
    const feats = activeAt[i].map((inc) => ({
      type: "Feature", geometry: { type: "Point", coordinates: [inc.lon, inc.lat] },
      properties: { id: inc.id, scope: inc.scope, priority: inc.priority },
    }));
    return { type: "FeatureCollection", features: feats };
  }

  // ------------------------------------------------------------------ map
  const map = new maplibregl.Map({
    container: "map",
    style: "https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json",
    ...HOME, maxPitch: 75, antialias: true, attributionControl: { compact: true },
  });
  map.addControl(new maplibregl.NavigationControl({ visualizePitch: true }), "top-left");
  map.addControl(new maplibregl.ScaleControl({ unit: "imperial" }), "bottom-right");

  const BLDG_COLOR = {
    risk: ["interpolate", ["linear"], ["coalesce", ["get", "risk"], 0], 15, "#23405a", 30, "#3d7fa8", 45, "#f2b544", 60, "#ef5a45"],
    condition: ["interpolate", ["linear"], ["coalesce", ["get", "condition"], 70], 20, "#ef5a45", 50, "#f2b544", 75, "#3d9ab8", 95, "#2dd4bf"],
    age: ["interpolate", ["linear"], ["coalesce", ["get", "year_built"], 1970], 1890, "#b45309", 1940, "#f59e0b", 1980, "#64748b", 2020, "#38bdf8"],
  };
  const LEGENDS = {
    risk: ["Composite risk (condition · criticality · anomalies)", "linear-gradient(90deg,#23405a,#3d7fa8,#f2b544,#ef5a45)", "Low", "High"],
    condition: ["Building condition score", "linear-gradient(90deg,#ef5a45,#f2b544,#3d9ab8,#2dd4bf)", "Poor", "Good"],
    age: ["Year built", "linear-gradient(90deg,#b45309,#f59e0b,#64748b,#38bdf8)", "1890", "2020"],
  };

  const LAYERS = [
    { id: "ix-hotspots", label: "Risk hot-spots (Gi*)", color: "#ef5a45", on: false, count: D.hotspots.filter((h) => h.class === "hot").length },
    { id: "ix-buildings", label: "Buildings (3D)", color: "#3d7fa8", on: true, count: byType("building").length },
    { id: "ix-roads", label: "Roads – pavement condition", color: "#94a3b8", on: true, count: byType("road").length },
    { id: "ix-water", label: "Water mains", color: "#4aa3ff", on: true, count: byType("water_main").length },
    { id: "ix-rail", label: "Rail (BNSF)", color: "#a78bfa", on: true, count: byType("ix-rail").length },
    { id: "ix-hydrants", label: "Hydrants", color: "#60a5fa", on: false, count: byType("hydrant").length },
    { id: "ix-lights", label: "Streetlights", color: "#ffd166", on: false, count: byType("streetlight").length },
    { id: "ix-sensors", label: "IoT sensors (3D)", color: "#2dd4bf", on: true, count: D.sensors.length },
    { id: "ix-incidents", label: "Active incidents", color: "#ef5a45", on: true, count: D.incidents.length },
  ];
  const LAYER_IDS = { "ix-incidents": ["ix-incident-pulse", "ix-incident-core"] };

  map.on("load", () => {
    const fc = (t) => ({ type: "FeatureCollection", features: byType(t) });
    const firstSymbol = map.getStyle().layers.find((l) => l.type === "symbol")?.id;

    map.addSource("ix-sat", { type: "raster", tileSize: 256, maxzoom: 19,
      tiles: ["https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"],
      attribution: "Imagery © Esri, Maxar, Earthstar Geographics" });
    map.addLayer({ id: "ix-sat", type: "raster", source: "ix-sat", layout: { visibility: "none" }, paint: { "raster-opacity": 0.85 } }, firstSymbol);

    map.addSource("ix-hotspots", { type: "geojson", data: { type: "FeatureCollection", features: D.hotspots.filter((h) => h.class !== "ns").map((h) => ({
      type: "Feature", geometry: { type: "Polygon", coordinates: [h.polygon] }, properties: h })) } });
    map.addLayer({ id: "ix-hotspots", type: "fill-extrusion", source: "ix-hotspots", layout: { visibility: "none" }, paint: {
      "fill-extrusion-color": ["case", [">", ["get", "gi_z"], 0], ["interpolate", ["linear"], ["get", "gi_z"], 1.96, "#f59e0b", 3.5, "#ef4444"], "#38bdf8"],
      "fill-extrusion-height": ["*", ["abs", ["get", "gi_z"]], 12], "fill-extrusion-opacity": 0.35 } });

    map.addSource("ix-roads", { type: "geojson", data: fc("road") });
    map.addLayer({ id: "ix-roads", type: "line", source: "ix-roads", layout: { "line-cap": "round", "line-join": "round" }, paint: {
      "line-color": ["interpolate", ["linear"], ["get", "pci"], 40, "#ef5a45", 60, "#f2b544", 80, "#7dd3a8", 95, "#2dd4bf"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 13, ["*", 0.5, ["get", "road_class"]], 17, ["*", 2.4, ["get", "road_class"]]],
      "line-opacity": 0.75 } }, firstSymbol);

    map.addSource("ix-rail", { type: "geojson", data: fc("ix-rail") });
    map.addLayer({ id: "ix-rail", type: "line", source: "ix-rail", paint: { "line-color": "#a78bfa", "line-width": 2, "line-dasharray": [2, 1.5] } }, firstSymbol);

    map.addSource("ix-water", { type: "geojson", data: fc("water_main") });
    map.addLayer({ id: "ix-water", type: "line", source: "ix-water", paint: {
      "line-color": ["match", ["get", "risk_class"], "high", "#ef5a45", "medium", "#f2b544", "#4aa3ff"],
      "line-width": ["interpolate", ["linear"], ["zoom"], 13, 1, 17, ["/", ["get", "diameter_in"], 3]],
      "line-opacity": 0.9 } });

    map.addSource("ix-hydrants", { type: "geojson", data: fc("hydrant") });
    map.addLayer({ id: "ix-hydrants", type: "circle", source: "ix-hydrants", layout: { visibility: "none" }, paint: {
      "circle-radius": ["interpolate", ["linear"], ["zoom"], 14, 1.5, 18, 5], "circle-color": "#60a5fa",
      "circle-stroke-color": "#0b1016", "circle-stroke-width": 0.5 } });

    map.addSource("ix-lights", { type: "geojson", data: fc("streetlight") });
    map.addLayer({ id: "ix-lights", type: "circle", source: "ix-lights", layout: { visibility: "none" }, paint: {
      "circle-radius": ["interpolate", ["linear"], ["zoom"], 14, 1.2, 18, 4],
      "circle-color": ["match", ["get", "lamp"], "LED", "#fff3c4", "#ffb347"], "circle-blur": 0.3 } });

    map.addSource("ix-buildings", { type: "geojson", data: fc("building") });
    map.addLayer({ id: "ix-buildings", type: "fill-extrusion", source: "ix-buildings", paint: {
      "fill-extrusion-color": ["case", ["boolean", ["feature-state", "sel"], false], "#ffffff", BLDG_COLOR.risk],
      "fill-extrusion-height": ["get", "height_m"], "fill-extrusion-opacity": 0.88,
      "fill-extrusion-vertical-gradient": true } });

    map.addSource("ix-sensors", { type: "geojson", data: sensorGeoJSON(0) });
    map.addLayer({ id: "ix-sensors", type: "fill-extrusion", source: "ix-sensors", paint: {
      "fill-extrusion-color": ["get", "color"], "fill-extrusion-height": ["get", "h"],
      "fill-extrusion-base": 0, "fill-extrusion-opacity": 0.95 } });

    map.addSource("ix-incidents", { type: "geojson", data: incidentPoints(0) });
    map.addLayer({ id: "ix-incident-pulse", type: "circle", source: "ix-incidents", paint: {
      "circle-radius": 10, "circle-color": "transparent", "circle-stroke-width": 2,
      "circle-stroke-color": ["match", ["get", "scope"], "area-wide", "#38bdf8", "#ef5a45"], "circle-pitch-alignment": "map" } });
    map.addLayer({ id: "ix-incident-core", type: "circle", source: "ix-incidents", paint: {
      "circle-radius": 4, "circle-color": ["match", ["get", "scope"], "area-wide", "#38bdf8", "#ef5a45"], "circle-pitch-alignment": "map" } });

    wireMapInteractions();
    buildLayerList();
    pulse();
    const firstArea = D.incidents.find((i) => i.diagnosis === "pump_station_trip");
    setTime(firstArea ? firstArea.start_idx + 1 : N - 1);
    document.getElementById("loading").remove();
  });

  function pulse() {
    const t = (performance.now() % 1600) / 1600;
    if (map.getLayer("ix-incident-pulse")) {
      map.setPaintProperty("ix-incident-pulse", "circle-radius", 6 + t * 22);
      map.setPaintProperty("ix-incident-pulse", "circle-stroke-opacity", 1 - t);
    }
    requestAnimationFrame(pulse);
  }

  // ------------------------------------------------------------------ popups & clicks
  const popup = new maplibregl.Popup({ closeButton: true, maxWidth: "280px" });
  function rows(obj) {
    return "<table>" + Object.entries(obj).filter(([, v]) => v !== undefined && v !== null && v !== "")
      .map(([k, v]) => `<tr><td>${esc(k)}</td><td>${esc(v)}</td></tr>`).join("") + "</table>";
  }
  function assetPopup(p) {
    const common = { "Asset ID": p.id, Risk: p.risk != null ? `${p.risk} (${p.risk_class})` : undefined };
    const byKind = {
      building: { Type: p.building_type, Height: `${p.height_m} m${p.height_estimated ? " (est.)" : ""}`, Footprint: `${num(p.footprint_m2, 0)} m²`, "Year built": p.year_built, Condition: p.condition, Criticality: p.criticality },
      road: { Class: p.highway, Length: `${num(p.length_m, 0)} m`, PCI: p.pci, AADT: num(p.aadt, 0), Resurfaced: p.last_resurfaced, Lanes: p.lanes },
      water_main: { Diameter: `${p.diameter_in}″`, Material: p.material, Installed: p.install_year, "Break history": p.break_history, Condition: p.condition, Zone: p.pressure_zone },
      hydrant: { "Fire flow": `${p.flow_gpm} gpm`, Main: p.main_id, Zone: p.pressure_zone },
      streetlight: { Lamp: `${p.lamp} ${p.wattage} W`, Installed: p.install_year, Condition: p.condition },
      rail: { Operator: p.operator, Length: `${num(p.length_m, 0)} m` },
    }[p.type] || {};
    const src = p.synthetic ? "<div style='color:var(--warn);font-size:11px;margin-top:6px'>Derived / simulated attribute data</div>"
      : "<div style='color:var(--muted);font-size:11px;margin-top:6px'>Geometry © OpenStreetMap contributors</div>";
    return `<div class="pop"><h3>${esc(p.name || p.type.replace("_", " "))}</h3>${rows({ ...common, ...byKind })}${src}</div>`;
  }

  let selBldg = null;
  function wireMapInteractions() {
    ["ix-buildings", "ix-roads", "ix-water", "ix-hydrants", "ix-lights", "ix-rail", "ix-sensors", "ix-incident-core", "ix-hotspots"].forEach((id) => {
      map.on("mouseenter", id, () => (map.getCanvas().style.cursor = "pointer"));
      map.on("mouseleave", id, () => (map.getCanvas().style.cursor = ""));
    });
    map.on("click", (e) => {
      const hits = map.queryRenderedFeatures(e.point, { layers: ["ix-incident-core", "ix-sensors", "ix-hydrants", "ix-lights", "ix-water", "ix-roads", "ix-rail", "ix-buildings", "ix-hotspots"].filter((l) => map.getLayer(l) && map.getLayoutProperty(l, "visibility") !== "none") });
      if (!hits.length) return;
      const f = hits[0];
      if (f.layer.id === "ix-incident-core") return selectIncident(D.incidents.find((i) => i.id === f.properties.id), false);
      if (f.layer.id === "ix-sensors") return selectSensor(f.properties.id, false);
      if (f.layer.id === "ix-hotspots") {
        const h = f.properties;
        return popup.setLngLat(e.lngLat).setHTML(`<div class="pop"><h3>Getis-Ord Gi* cell</h3>${rows({ "Gi* z-score": h.gi_z, Class: h.class === "hot" ? "Hot-spot (p < 0.05)" : "Cold-spot (p < 0.05)", "Mean asset risk": h.mean_risk, Assets: h.n_assets })}</div>`).addTo(map);
      }
      if (f.layer.id === "ix-buildings") {
        if (selBldg != null) map.setFeatureState({ source: "ix-buildings", id: selBldg }, { sel: false });
        selBldg = f.id;
        map.setFeatureState({ source: "ix-buildings", id: selBldg }, { sel: true });
      }
      popup.setLngLat(e.lngLat).setHTML(assetPopup(f.properties)).addTo(map);
    });
  }

  // ------------------------------------------------------------------ left panel
  function buildLayerList() {
    const el = document.getElementById("layer-list");
    el.innerHTML = LAYERS.map((l) => `<label class="layer"><input type="checkbox" data-id="${l.id}" ${l.on ? "checked" : ""}>
      <span class="sw" style="background:${l.color}"></span>${l.label}<span class="n">${num(l.count, 0)}</span></label>`).join("");
    el.addEventListener("change", (e) => {
      const id = e.target.dataset.id;
      (LAYER_IDS[id] || [id]).forEach((lid) => map.setLayoutProperty(lid, "visibility", e.target.checked ? "visible" : "none"));
      if (id === "ix-hotspots") renderLegend();
    });
  }

  document.getElementById("bldg-mode").addEventListener("click", (e) => {
    const m = e.target.dataset.mode;
    if (!m) return;
    state.bldgMode = m;
    document.querySelectorAll("#bldg-mode button").forEach((b) => b.classList.toggle("on", b.dataset.mode === m));
    map.setPaintProperty("ix-buildings", "fill-extrusion-color", ["case", ["boolean", ["feature-state", "sel"], false], "#ffffff", BLDG_COLOR[m]]);
    renderLegend();
  });
  document.getElementById("basemap-sat").addEventListener("change", (e) => map.setLayoutProperty("ix-sat", "visibility", e.target.checked ? "visible" : "none"));
  document.getElementById("btn-home").addEventListener("click", () => map.flyTo({ ...HOME, duration: 1400 }));
  document.getElementById("btn-3d").addEventListener("click", (e) => {
    state.pitched = !state.pitched;
    e.currentTarget.textContent = state.pitched ? "3D" : "2D";
    map.easeTo({ pitch: state.pitched ? 58 : 0, bearing: state.pitched ? -22 : 0, duration: 800 });
  });

  function renderLegend() {
    const [title, grad, lo, hi] = LEGENDS[state.bldgMode];
    const types = Object.values(TYPE).map((t) => `<div class="row"><span class="dot" style="background:${t.color}"></span>${t.short}</div>`).join("");
    document.getElementById("legend").innerHTML = `
      <div><b>Buildings</b> – ${title}</div><div class="ramp" style="background:${grad}"></div><div class="ends"><span>${lo}</span><span>${hi}</span></div>
      <div style="margin-top:8px"><b>Sensor columns</b> – height = |anomaly z|</div>
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:0 8px">${types}
        <div class="row"><span class="dot" style="background:var(--warn)"></span>Warning</div>
        <div class="row"><span class="dot" style="background:var(--bad)"></span>Alarm</div>
        <div class="row"><span class="dot" style="background:var(--off)"></span>Offline</div></div>`;
  }

  function renderKPIs() {
    const i = state.t;
    const active = activeAt[i];
    const local = active.filter((x) => x.scope === "local").length;
    const area = new Set(active.filter((x) => x.scope === "area-wide").map((x) => x.event_id)).size;
    let offline = 0, alarm = 0;
    D.sensors.forEach((s) => { const st = sensorStatus(s, i); if (st === "offline") offline++; if (st === "alarm") alarm++; });
    const tiles = [
      ["Assets monitored", num(D.assets.features.length, 0), ""],
      ["Sensors online", `${D.sensors.length - offline}/${D.sensors.length}`, offline ? "warn" : ""],
      ["Active incidents", local, local ? "alert" : ""],
      ["Area-wide events", area, area ? "warn" : ""],
      ["High-risk assets", num(D.summary.high_risk_assets, 0), ""],
      ["Avg road PCI", num(D.summary.avg_pci), ""],
    ];
    document.getElementById("kpis").innerHTML = tiles.map(([l, v, c]) => `<div class="kpi ${c}"><div class="v">${v}</div><div class="l">${l}</div></div>`).join("");
  }

  function renderMetrics() {
    const m = D.metrics;
    const bar = (v) => `<div class="bar"><i style="width:${v * 100}%"></i></div>`;
    document.getElementById("metrics").innerHTML = `
      <div class="metric"><div class="l">Event recall</div><div class="v">${(m.event_recall * 100).toFixed(0)}%</div>${bar(m.event_recall)}</div>
      <div class="metric"><div class="l">Incident precision</div><div class="v">${(m.incident_precision * 100).toFixed(0)}%</div>${bar(m.incident_precision)}</div>
      <div class="metric"><div class="l">Root-cause accuracy</div><div class="v">${(m.diagnosis_accuracy * 100).toFixed(0)}%</div>${bar(m.diagnosis_accuracy)}</div>
      <div class="metric"><div class="l">Hourly F1</div><div class="v">${(2 * m.point_precision * m.point_recall / (m.point_precision + m.point_recall) * 100).toFixed(0)}%</div>${bar(2 * m.point_precision * m.point_recall / (m.point_precision + m.point_recall))}</div>
      <div class="metric full"><div class="l">${m.events_detected} of ${m.fault_events} injected faults detected · zone-wide pump trip ${m.zone_event_detected ? "identified as area-wide ✓" : "missed"}</div></div>
      <div class="metric full"><div class="l" style="line-height:1.5">Seasonal robust-z + Isolation Forest, with spatial consensus to separate area-wide events from single-asset faults.</div></div>`;
  }

  // ------------------------------------------------------------------ incident feed
  function buildTypeFilter() {
    const el = document.getElementById("type-filter");
    el.innerHTML = Object.entries(TYPE).map(([k, t]) => `<button class="chip on" data-t="${k}"><i style="background:${t.color}"></i>${t.short}</button>`).join("");
    el.addEventListener("click", (e) => {
      const b = e.target.closest(".chip");
      if (!b) return;
      const k = b.dataset.t;
      state.types.has(k) ? state.types.delete(k) : state.types.add(k);
      b.classList.toggle("on");
      renderFeed();
    });
  }
  document.getElementById("active-only").addEventListener("change", (e) => { state.activeOnly = e.target.checked; renderFeed(); });

  function renderFeed() {
    let list = state.activeOnly ? activeAt[state.t] : D.incidents.filter((i) => i.start_idx <= state.t);
    list = list.filter((i) => state.types.has(i.sensor_type));
    // collapse area-wide incidents (one per sensor) into a single row per physical event
    const members = {};
    list = list.filter((i) => {
      if (i.scope !== "area-wide") return true;
      (members[i.event_id] ||= []).push(i);
      return members[i.event_id].length === 1;
    }).sort((a, b) => b.priority - a.priority || b.start_idx - a.start_idx);
    document.getElementById("inc-count").textContent = list.length;
    const el = document.getElementById("feed");
    if (!list.length) {
      el.innerHTML = `<li class="empty">${state.activeOnly ? "No active incidents at this hour. Untick “Active now” to see history." : "No incidents yet."}</li>`;
      return;
    }
    el.innerHTML = list.slice(0, 150).map((i) => `
      <li data-id="${i.id}" style="border-left-color:${TYPE[i.sensor_type].color}" class="${state.selected === i.id ? "sel" : ""}">
        <div class="t1"><span class="d">${FAULT_LABEL[i.diagnosis] || i.diagnosis}</span><span class="p ${prClass(i.priority)}">P${i.priority}</span></div>
        <div class="t2">${i.scope === "area-wide" ? `${i.event_id} · area-wide · ${new Set(members[i.event_id].map((m) => m.sensor_id)).size} sensor(s)` : `${i.sensor_id} · ${esc(assetById[i.asset_id]?.properties.name || i.asset_id)}`} · ${fmtShort(times[i.start_idx])} · ${i.hours} h</div>
      </li>`).join("");
  }
  document.getElementById("feed").addEventListener("click", (e) => {
    const li = e.target.closest("li[data-id]");
    if (li) selectIncident(D.incidents.find((i) => i.id === li.dataset.id), true);
  });

  // ------------------------------------------------------------------ detail panel
  function selectIncident(inc, fly) {
    state.selected = inc.id;
    if (fly) map.flyTo({ center: [inc.lon, inc.lat], zoom: 17, pitch: 60, duration: 1200 });
    if (state.t < inc.start_idx || state.t > inc.end_idx) setTime(Math.min(inc.end_idx, inc.start_idx + 1));
    renderDetail(sensorsById[inc.sensor_id], inc);
    renderFeed();
  }
  function selectSensor(id, fly) {
    const s = sensorsById[id];
    const inc = activeAt[state.t].find((x) => x.sensor_id === id);
    state.selected = inc ? inc.id : null;
    if (fly) map.flyTo({ center: [s.lon, s.lat], zoom: 17, duration: 1200 });
    renderDetail(s, inc);
    renderFeed();
  }

  let detailSensor = null, detailInc = null;
  function renderDetail(s, inc) {
    detailSensor = s; detailInc = inc;
    const el = document.getElementById("detail");
    el.classList.remove("hidden");
    const asset = assetById[s.asset_id]?.properties || {};
    const i = state.t;
    const st = sensorStatus(s, i);
    const dx = inc
      ? `<div class="dx ${inc.scope === "area-wide" ? "area" : ""}"><b>${esc(inc.description)}</b><br><span style="color:var(--muted);font-size:12px">${inc.scope === "area-wide" ? `${inc.event_id} · ${new Set(D.incidents.filter((x) => x.event_id === inc.event_id).map((x) => x.sensor_id)).size} sensor(s) flagged` : `${inc.id} · local`} · ${fmtShort(times[inc.start_idx])} → ${fmtShort(times[inc.end_idx])}</span></div>`
      : `<div class="dx ok">Status: <b>${st}</b> – no incident on this sensor at the selected hour.</div>`;
    const stats = inc
      ? [["Peak", `${num(inc.peak_value)} `], ["Expected", num(inc.expected)], ["Peak z", num(inc.peak_z)], ["Duration", `${inc.hours} h`], ["Priority", inc.priority], ["Bldgs nearby", inc.impacted_buildings]]
      : [["Now", num(s.values[i])], ["Expected", num(s.expected[i])], ["z-score", num(s.z[i])], ["Battery", s.battery_pct != null ? s.battery_pct + "%" : "mains"], ["Installed", s.install_date.slice(0, 7)], ["Asset risk", asset.risk ?? "—"]];
    el.innerHTML = `
      <button class="close" aria-label="Close">×</button>
      <h3>${s.id} · ${TYPE[s.type].label}</h3>
      <div class="meta">${esc(s.description)} on ${esc(asset.name || s.asset_id)} (${s.asset_id}) · ${s.unit}</div>
      ${dx}
      <div class="stats">${stats.map(([l, v]) => `<div><b>${v}</b><span>${l}</span></div>`).join("")}</div>
      ${chartSVG(s, inc)}
      <div class="chart-legend"><span><i style="background:${TYPE[s.type].color}"></i>Observed</span><span><i style="background:#8a9bb0"></i>Expected (seasonal)</span><span><i style="background:var(--bad)"></i>Flagged</span></div>
      ${inc ? `<div class="action"><b>Recommended action:</b> ${ACTIONS[inc.diagnosis] || "Investigate."}</div>` : ""}`;
    el.querySelector(".close").onclick = () => { el.classList.add("hidden"); state.selected = null; detailSensor = null; renderFeed(); };
  }

  function chartSVG(s, inc) {
    const W = 330, H = 130, P = { l: 34, r: 6, t: 8, b: 18 };
    // Window: whole series, or ±48 h around the incident
    const a = inc ? Math.max(0, inc.start_idx - 48) : 0;
    const b = inc ? Math.min(N - 1, inc.end_idx + 48) : N - 1;
    const vals = s.values.slice(a, b + 1), exp = s.expected.slice(a, b + 1);
    const all = vals.concat(exp).filter((v) => v != null);
    let lo = Math.min(...all), hi = Math.max(...all);
    if (hi - lo < 1e-6) { hi += 1; lo -= 1; }
    const pad = (hi - lo) * 0.08; lo -= pad; hi += pad;
    const x = (k) => P.l + ((k - a) / Math.max(1, b - a)) * (W - P.l - P.r);
    const y = (v) => P.t + (1 - (v - lo) / (hi - lo)) * (H - P.t - P.b);
    const path = (arr) => { let d = "", pen = false; arr.forEach((v, j) => { if (v == null) { pen = false; return; } d += `${pen ? "L" : "M"}${x(a + j).toFixed(1)},${y(v).toFixed(1)}`; pen = true; }); return d; };
    const flagged = D.incidents.filter((q) => q.sensor_id === s.id && q.end_idx >= a && q.start_idx <= b)
      .map((q) => `<rect x="${x(Math.max(a, q.start_idx))}" y="${P.t}" width="${Math.max(2, x(Math.min(b, q.end_idx)) - x(Math.max(a, q.start_idx)))}" height="${H - P.t - P.b}" fill="rgba(239,90,69,.16)"/>`).join("");
    const ticks = [lo + pad, (lo + hi) / 2, hi - pad];
    const days = [];
    for (let k = a; k <= b; k++) if (times[k].getUTCHours() === 0) days.push(k);
    const step = Math.ceil(days.length / 5) || 1;
    const now = state.t >= a && state.t <= b ? `<line x1="${x(state.t)}" x2="${x(state.t)}" y1="${P.t}" y2="${H - P.b}" stroke="#e6edf5" stroke-dasharray="2 2" opacity=".6"/>` : "";
    return `<svg class="chart" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" role="img" aria-label="Sensor time series">
      ${flagged}
      ${ticks.map((v) => `<line x1="${P.l}" x2="${W - P.r}" y1="${y(v)}" y2="${y(v)}" stroke="#233142"/><text x="${P.l - 4}" y="${y(v) + 3}" fill="#8a9bb0" font-size="9" text-anchor="end">${num(v, v < 10 ? 2 : 0)}</text>`).join("")}
      ${days.filter((_, j) => j % step === 0).map((k) => `<text x="${x(k)}" y="${H - 5}" fill="#8a9bb0" font-size="9" text-anchor="middle">${times[k].toLocaleDateString("en-US", { month: "short", day: "numeric", timeZone: "UTC" })}</text>`).join("")}
      <path d="${path(exp)}" fill="none" stroke="#8a9bb0" stroke-width="1" stroke-dasharray="3 2"/>
      <path d="${path(vals)}" fill="none" stroke="${TYPE[s.type].color}" stroke-width="1.4"/>
      ${now}
    </svg>`;
  }

  // ------------------------------------------------------------------ timeline
  const slider = document.getElementById("slider");
  slider.max = N - 1;
  slider.addEventListener("input", () => setTime(+slider.value));

  function drawHistogram() {
    const c = document.getElementById("histogram");
    const dpr = window.devicePixelRatio || 1;
    const w = c.clientWidth, h = c.clientHeight;
    c.width = w * dpr; c.height = h * dpr;
    const g = c.getContext("2d");
    g.scale(dpr, dpr);
    const counts = activeAt.map((l) => [l.filter((x) => x.scope === "local").length, l.filter((x) => x.scope !== "local").length]);
    const max = Math.max(...counts.map((c) => c[0] + c[1]), 1);
    const bw = w / N;
    // day/night shading
    times.forEach((t, i) => { const hr = t.getUTCHours(); if (hr < 6 || hr >= 20) { g.fillStyle = "rgba(255,255,255,.025)"; g.fillRect(i * bw, 0, bw + 0.5, h); } });
    counts.forEach(([loc, area], i) => {
      const hl = (loc / max) * (h - 4), ha = (area / max) * (h - 4);
      g.fillStyle = "#ef5a45"; g.fillRect(i * bw, h - hl, Math.max(1, bw - 0.3), hl);
      g.fillStyle = "#38bdf8"; g.fillRect(i * bw, h - hl - ha, Math.max(1, bw - 0.3), ha);
    });
    const x = (state.t + 0.5) * bw;
    g.strokeStyle = "#e6edf5"; g.lineWidth = 1.5; g.beginPath(); g.moveTo(x, 0); g.lineTo(x, h); g.stroke();
    const labels = document.getElementById("tl-labels");
    labels.innerHTML = times.map((t, i) => (t.getUTCHours() === 0 && i % 48 === 0 ? `<span style="left:${(i / N) * 100}%">${t.toLocaleDateString("en-US", { month: "short", day: "numeric", timeZone: "UTC" })}</span>` : "")).join("");
  }
  window.addEventListener("resize", drawHistogram);

  function setTime(i) {
    state.t = Math.max(0, Math.min(N - 1, i));
    slider.value = state.t;
    document.getElementById("t-date").textContent = fmtDate(times[state.t]);
    document.getElementById("t-hour").textContent = fmtHour(times[state.t]);
    if (map.getSource("ix-sensors")) {
      map.getSource("ix-sensors").setData(sensorGeoJSON(state.t));
      map.getSource("ix-incidents").setData(incidentPoints(state.t));
    }
    renderKPIs();
    renderFeed();
    drawHistogram();
    if (detailSensor) renderDetail(detailSensor, detailInc && state.t >= detailInc.start_idx && state.t <= detailInc.end_idx ? detailInc : activeAt[state.t].find((x) => x.sensor_id === detailSensor.id));
  }

  // playback
  const playBtn = document.getElementById("btn-play");
  function togglePlay() {
    state.playing = !state.playing;
    document.getElementById("play-icon").setAttribute("d", state.playing ? "M6 4h4v16H6zM14 4h4v16h-4z" : "M7 4l13 8-13 8z");
    playBtn.setAttribute("aria-label", state.playing ? "Pause" : "Play");
    clearInterval(state.timer);
    if (state.playing) state.timer = setInterval(() => setTime(state.t >= N - 1 ? 0 : state.t + 1), +document.getElementById("speed").value);
  }
  playBtn.addEventListener("click", togglePlay);
  document.getElementById("speed").addEventListener("change", () => { if (state.playing) { togglePlay(); togglePlay(); } });
  document.addEventListener("keydown", (e) => {
    if (e.target.tagName === "INPUT" && e.target.type !== "range") return;
    if (e.code === "Space") { e.preventDefault(); togglePlay(); }
    if (e.code === "ArrowRight") setTime(state.t + 1);
    if (e.code === "ArrowLeft") setTime(state.t - 1);
  });

  // ------------------------------------------------------------------ init
  document.getElementById("src-badge").textContent = D.meta.source === "OpenStreetMap" ? "OSM + simulated IoT" : "Synthetic demo data";
  buildTypeFilter();
  renderLegend();
  renderMetrics();
  renderKPIs();
})();
